export default {
    VIEW_BLOGS: "VIEWBLOGS",
    CREATE_BLOG: "CREATEBLOG",
    UPDATE_BLOG: "UPDATEBLOG",
    DELETE_BLOG: "DELETEBLOG",
    VIEW_POSTS: "VIEWPOSTS",
    CREATE_POST: "CREATEPOST",
    UPDATE_POST: "UPDATEPOST",
    DELETE_POST: "DELETEPOST"
}